### ISSUE TITLE
Entities using record.position as primary key

### ISSUE THREAD

**Issue by befer** [camunda-community-hub/zeeqs#214] opened 2022-02-09 16:33 UTC
First of all: great community project.

While evaluating a solution that replaces the Hazelcast exporter/importer with a Kafka based solution, I found the following entities using the position as the primary key:
- ElementInstanceStateTransition
- MessageCorrelation
- VariableUpdate

As far as I know, the position is unique per partition, which would mean that the key is not unique when multiple partitions are used. Shouldn't this be a compound key then ? 
For example for VariableUpdate, position+variableKey should be always unique.

**Comment by saig0** [comment] 2022-02-24 05:07
@befer thank you for raising this up :+1: 

> Shouldn't this be a compound key then ?

Yes. That is correct.

We had a [similar issue](https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/278) in the simple monitor project. We solved it by using a combination of `partition id` + `position`.

**Comment by saig0** [comment] 2022-06-07 04:51
Duplicate of #162

**Closed by saig0** 2022-06-07 04:51 UTC
Labels: bug, scope-hazelcast
